version: '3.8'

# Override pour le développement local
services:
  api:
    build:
      target: production  # ou builder pour le dev
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    volumes:
      - .:/usr/src/app
      - /usr/src/app/__pycache__  # Exclure le cache Python
    ports:
      - "5004:5000"
    command: python manage.py run -h 0.0.0.0 --reload
    develop:
      watch:
        - action: sync
          path: ./src
          target: /usr/src/app/src
        - action: rebuild
          path: requirements.txt

  api-db:
    environment:
      - POSTGRES_DB=api_dev
    ports:
      - "5432:5432"  # Exposer pour les outils externes
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

volumes:
  postgres_data_dev: 